services:
  youtube-data-kaggle:
    container_name: kaggle
    restart: always
    image: kaggle
    logging:
      options:
        max-size: "5m"
        max-file: "3"
    build:
      context: .
      args:
        POETRY_ARGS: ""
    tty: true
    working_dir: /opt/downloader/
    volumes:
      - ./downloader:/opt/downloader
    env_file: "compose.env"
